// @ts-check

import path from 'node:path'

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`

/** @type {import("esbuild").BuildOptions} */
export const sharedEsbuildConfig = {
  logLevel: 'info',
  banner: {
    js: banner,
  },
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
  ],
  bundle: true,
  entryPoints: ['src/TimecodesPlugin.ts'],
  format: 'cjs',
  target: 'es2018',
  minify: false,
  sourcemap: 'inline',
  treeShaking: true,
  outfile: path.join('out', 'main.js'),
}
