name: Release

on:
  push:
    tags:
      - '*'

env:
  PLUGIN_NAME: timecodes

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v5
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v5
        with:
          node-version: '22'
          package-manager-cache: false
      - name: Environment details
        run: pnpm version
      - name: Build
        id: build
        run: |
          pnpm install
          pnpm run build
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${GITHUB_REF#refs/tags/}"

          gh release create "$tag" \
            --title="$tag" \
            out/main.js manifest.json
